name: Node.js CI (KOO)

on:
  push:
    branches: [ "koo" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x,
      uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
